export const iconNames = [
  '22',
  'airplane',
  'arch',
  'archive-book',
  'areas',
  'attach',
  'award',
  'book',
  'bookmark',
  'box',
  'briefcase',
  'broom',
  'calendar',
  'chart',
  'check',
  'crown',
  'emacs',
  'eslint',
  'estateguru',
  'flash',
  'fullstacks',
  'github',
  'goal',
  'habit',
  'heart',
  'home',
  'html',
  'inbox',
  'infinity',
  'keyboard',
  'layer',
  'linux',
  'messages',
  'monitor-mobile',
  'monitor',
  'more',
  'notebook',
  'notes',
  'notion',
  'people',
  'planet',
  'python',
  'rain',
  'receipt-edit',
  'routine',
  'ruler-pen',
  'setting',
  'slack',
  'status-up',
  'teacher',
  'trash',
  'triangle',
  'user-group',
  'user-tag',
  'user',
  'video',
  'vim',
  'wallet',
  'youtube',
] as const;

export type IconName = typeof iconNames[number];

export const Icon = (name: IconName) =>
  `https://raw.githubusercontent.com/ASafaeirad/notion-icons/main/${name}.svg`;
